name: "Build And Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build And Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ] #  , macos-latest ]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/actions/setup-env
        with:
          os: ${{ runner.os }}

      - uses: ./.github/actions/3rd-party-libraries-download
        with:
          os: ${{ runner.os }}

      - uses: ./.github/actions/3rd-party-libraries-compile
        with:
          os: ${{ runner.os }}

      - uses: ./.github/actions/3rd-party-libraries-install
        with:
          os: ${{ runner.os }}

      - uses: ./.github/actions/compile-libraries
        with:
          os: ${{ runner.os }}

      - uses: ./.github/actions/run-linter
        with:
          os: ${{ runner.os }}

      - uses: ./.github/actions/validate-dependencies
        with:
          os: ${{ runner.os }}

      - uses: ./.github/actions/run-test
        with:
          os: ${{ runner.os }}
